#!/bin/bash

# Worker node setup script
source "$(dirname "$0")/common.sh"

set -e

MASTER_IP=$1

if [[ -z "$MASTER_IP" ]]; then
    log_error "Worker deployment requires the MASTER IP as the second argument."
    log_info "Usage: sudo ./ks_installer.sh worker <MASTER-IP>"
    exit 1
fi

log_info "Preparing worker node to join cluster at ${MASTER_IP}..."

echo "Waiting for join command..."
read -p "Paste the 'kubeadm join' command (generated by master): " JOIN_CMD

if [[ -z "$JOIN_CMD" ]]; then
    log_error "No join command provided. Exiting."
    exit 1
fi

log_info "Executing join command..."
eval "sudo $JOIN_CMD"

echo
echo "=================================="
echo "   WORKER JOINED SUCCESSFULLY     "
echo "=================================="
echo
